// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdZr6HKngMtKRjtLQZkWt62Y7AnzQLig',
    appId: '1:1081724332252:web:8a6add643552684a0eec19',
    messagingSenderId: '1081724332252',
    projectId: 'apraxiaapp',
    authDomain: 'apraxiaapp.firebaseapp.com',
    databaseURL: 'https://apraxiaapp-default-rtdb.firebaseio.com',
    storageBucket: 'apraxiaapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDApLJPUCZvQ7Pzmr9BlxkT02QFxQH4f7U',
    appId: '1:1081724332252:android:73e1afa3828589240eec19',
    messagingSenderId: '1081724332252',
    projectId: 'apraxiaapp',
    databaseURL: 'https://apraxiaapp-default-rtdb.firebaseio.com',
    storageBucket: 'apraxiaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEBBYkS4lK4IEKq_ACDxS4Yt7jHNAEnNw',
    appId: '1:1081724332252:ios:7b62954a0443a7040eec19',
    messagingSenderId: '1081724332252',
    projectId: 'apraxiaapp',
    databaseURL: 'https://apraxiaapp-default-rtdb.firebaseio.com',
    storageBucket: 'apraxiaapp.appspot.com',
    androidClientId: '1081724332252-0g6g2s4aa6acvqvu2ba0hl7ts6vohg9m.apps.googleusercontent.com',
    iosClientId: '1081724332252-3q333cgva3apnsnurklms80oq41v1j6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.appraxi',
  );
}
